{{- if not .Values.global.opentelemetry.disable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-otel-collector-secrets
  labels:
    app: {{ .Release.Name }}-opentelemetry
    component: {{ .Release.Name }}-otel-collector
type: Opaque
stringData:
  azure-monitor-connection-string: {{ .Values.global.opentelemetry.azuremonitor.connectionString | quote }}
{{- end }}
