{{- if not .Values.global.opentelemetry.disable }}
{{- if .Values.global.opentelemetry.collector.backends.azuremonitor.connectionString }}
#
# WARNING: This secret is created from values.yaml which is NOT SECURE.
# It is recommended to create this secret manually using kubectl before installation:
#
#   kubectl create secret generic {{ tpl .Values.global.opentelemetry.collector.backends.azuremonitor.secretName . }} \
#     --from-literal=connection-string='<your-connection-string>' \
#     -n <namespace>
#
# This template is only used if connectionString is explicitly set in values.yaml (not recommended).
#
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.global.opentelemetry.collector.backends.azuremonitor.secretName . }}
  labels:
    app: {{ .Release.Name }}-opentelemetry
    component: {{ .Release.Name }}-otel-collector
type: Opaque
stringData:
  connection-string: {{ .Values.global.opentelemetry.collector.backends.azuremonitor.connectionString | quote }}
{{- end }}
{{- end }}
