{{- if not .Values.global.opentelemetry.disable }}
{{- range .Values.global.opentelemetry.collector.backends }}
{{- if .connectionString }}
#
# WARNING: This secret is created from values.yaml which is NOT SECURE.
# It is recommended to create this secret manually using kubectl before installation:
#
#   kubectl create secret generic {{ tpl .secretName $ }} \
#     --from-literal=connection-string='<your-connection-string>' \
#     -n <namespace>
#
# This template is only used if connectionString is explicitly set in values.yaml (not recommended).
#
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .secretName $ }}
  labels:
    app: {{ $.Release.Name }}-opentelemetry
    component: {{ $.Release.Name }}-otel-collector
    backend-kind: {{ .kind }}
type: Opaque
stringData:
  connection-string: {{ .connectionString | quote }}
{{- end }}
{{- end }}
{{- end }}
