{{- if not .Values.global.opentelemetry.disable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-otel-collector
  labels:
    app: {{ .Release.Name }}-opentelemetry
    component: {{ .Release.Name }}-otel-collector
{{- end }}
