{{- if and (not .Values.global.opentelemetry.disable) .Values.global.opentelemetry.agent.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-otel-agent
  labels:
    app: {{ .Release.Name }}-opentelemetry
    component: {{ .Release.Name }}-otel-agent
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-opentelemetry
      component: {{ .Release.Name }}-otel-agent
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-opentelemetry
        component: {{ .Release.Name }}-otel-agent
    spec:
      containers:
      - command:
          - "/otelcol"
          - "--config=/conf/otel-agent-config.yaml"
        image: {{ include "otel.agent.image" . }}
        name: otel-agent
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 55679 # ZPages endpoint.
        - containerPort: 4317 # Default OpenTelemetry receiver port.
        - containerPort: 8888  # Metrics.
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: GOMEMLIMIT
            value: 400MiB
{{- if .Values.global.opentelemetry.collector.backends.googlecloud }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.opentelemetry.collector.backends.googlecloud.secretName . }}
                key: connection-string
{{- end }}
{{- if .Values.global.opentelemetry.collector.backends.azuremonitor }}
          - name: AZURE_MONITOR_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.opentelemetry.collector.backends.azuremonitor.secretName . }}
                key: connection-string
{{- end }}
        volumeMounts:
        - name: otel-agent-config-vol
          mountPath: /conf
      volumes:
        - configMap:
            name: otel-agent-conf
            items:
              - key: otel-agent-config
                path: otel-agent-config.yaml
          name: otel-agent-config-vol
{{- end }}