#       Copyright 2021 IBM Corp All Rights Reserved
#       Copyright 2025 Kyndryl, All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

{{- if .Values.global.istio }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  selector:
    istio: {{ .Values.global.istioIngress }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
{{- if .Values.trader.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-trader
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: /trader
    route:
    - destination:
        host: {{ .Release.Name }}-trader-service
        port:
          number: 9443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-trader
spec:
  host: {{ .Release.Name }}-trader-service
  subsets:
  - name: v1
    labels:
      version: v1
---
{{- end }}
{{- if .Values.tradr.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-tradr
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: /tradr
    route:
    - destination:
        host: {{ .Release.Name }}-tradr-service
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-tradr
spec:
  host: {{ .Release.Name }}-tradr-service
  subsets:
  - name: v1
    labels:
      version: v1
---
{{- end }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-broker
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: /broker
    route:
    - destination:
        host: {{ .Release.Name }}-broker-service
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-broker
spec:
  host: {{ .Release.Name }}-broker-service
  subsets:
  - name: v1
    labels:
      version: v1
---
{{- if .Values.looper.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-looper
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: /looper
    route:
    - destination:
        host: {{ .Release.Name }}-looper-service
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-looper
spec:
  host: {{ .Release.Name }}-looper-service
  subsets:
  - name: v1
    labels:
      version: v1
---
{{- end }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-istio
  labels:
    app: istio
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/instance: {{ .Values.global.istioNamespace }}
    release: istio
    maistra.io/member-of: {{ .Values.global.istioNamespace }}
    app.kubernetes.io/component: {{ .Values.global.istioNamespace }}-config
    app.kubernetes.io/managed-by: maistra-istio-operator
    maistra.io/owner: {{ .Values.global.istioNamespace }}
    app.kubernetes.io/name: {{ .Values.global.istioNamespace }}-config
spec:
  podSelector: {{ print "{}" }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              maistra.io/member-of: {{ .Values.global.istioNamespace }}
  policyTypes:
    - Ingress
{{- if .Values.global.route }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-istio-expose-route
  labels:
    app: istio
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/instance: {{ .Values.global.istioNamespace }}
    release: istio
    maistra.io/member-of: {{ .Values.global.istioNamespace }}
    app.kubernetes.io/component: {{ .Values.global.istioNamespace }}-config
    app.kubernetes.io/managed-by: maistra-istio-operator
    maistra.io/owner: {{ .Values.global.istioNamespace }}
    app.kubernetes.io/name: {{ .Values.global.istioNamespace }}-config
spec:
  podSelector:
    matchLabels:
      maistra.io/expose-route: 'true'
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress
{{- end }}
{{- end }}
