#       Copyright 2020-2021 IBM Corp, All Rights Reserved
#       Copyright 2022-2023 Kyndryl, All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

{{- if .Values.tradeHistory.enabled }}
#Deploy the pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-trade-history
  labels:
    app: {{ .Release.Name }}-stock-trader
  annotations:
    prism.subkind: Liberty
spec:
{{- if not .Values.tradeHistory.autoscale }}
  replicas: {{ .Values.tradeHistory.replicas }}
{{- end }}
  selector:
    matchLabels:
      app: trade-history
  template:
    metadata:
      labels:
        app: trade-history
      annotations:
        git-repo: "https://github.com/IBMStockTrader/trade-history"
{{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-stocktrader-secrets.txt: {{ .Values.vault.path }}
        vault.hashicorp.com/agent-inject-template-stocktrader-secrets.txt: |
          {{"{{"}}- with secret "{{ .Values.vault.path }}" -{{"}}"}}
          export MONGO_USER={{"{{"}} .Data.data.mongoUser {{"}}"}}
          export MONGO_PASSWORD={{"{{"}} .Data.data.mongoPassword {{"}}"}}
          export KAFKA_USER={{"{{"}} .Data.data.kafkaUser {{"}}"}}
          export CONSUMER_API_KEY={{"{{"}} .Data.data.kafkaApiKey {{"}}"}}
          {{"{{"}}- end -{{"}}"}}
        vault.hashicorp.com/role: {{ .Values.vault.role }}
{{- end }}
{{- if .Values.global.monitoring }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: "9080"
{{- end }}
{{- if .Values.global.istio }}
        sidecar.istio.io/inject: 'true'
{{- end }}
    spec:
{{- if .Values.global.pullSecret }}
      imagePullSecrets:
      - name: {{ tpl .Values.global.pullSecretName . }}
{{- end }}
      containers:
      - name: trade-history
        image: "{{ .Values.tradeHistory.image.repository }}:{{ .Values.tradeHistory.image.tag }}"
{{- if .Values.vault.enabled }}
        args:
          - sh
          - '-c'
          - source /vault/secrets/stocktrader-secrets.txt && /opt/ol/helpers/runtime/docker-server.sh /opt/ol/wlp/bin/server run defaultServer
{{- end }}
        env:
          - name: AUTH_TYPE
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: auth.type
          - name: TRACE_SPEC
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: trace.spec
                optional: true
          - name: JWT_AUDIENCE
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }} 
                key: jwt.audience
          - name: JWT_ISSUER
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: jwt.issuer
          - name: OIDC_JWKS_URL
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: oidc.jwksUrl
                optional: true
          - name: STOCK_QUOTE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: stockQuote.url
                optional: true
{{- if not .Values.vault.enabled }}
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: mongo.user
                optional: false
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: mongo.password
                optional: false
          - name: KAFKA_USER
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: kafka.user
                optional: true
          - name: CONSUMER_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: kafka.apiKey
                optional: false
{{- end }}
          - name: MONGO_AUTH_DB
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: mongo.authDB
                optional: false
          - name: MONGO_DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: mongo.database
                optional: false
          - name: MONGO_IP
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: mongo.ip
                optional: false
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: mongo.port
                optional: false
          - name: MP_MESSAGING_CONNECTOR_LIBERTY_KAFKA_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.address
                optional: false
          - name: MP_MESSAGING_CONNECTOR_LIBERTY_KAFKA_SASL_JAAS_CONFIG
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.saslJaasConfig
                optional: false
          - name: MP_MESSAGING_CONNECTOR_LIBERTY_KAFKA_SASL_MECHANISM
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.saslMechanism
                optional: false
          - name: MP_MESSAGING_INCOMING_STOCKTRADER_TOPIC
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.historyTopic 
                optional: false
{{- if .Values.global.specifyCerts }}
          - name: cert_defaultTrustStore
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: ssl.certs
                optional: true
{{- end }}
{{- if .Values.global.jsonLogging }}
          - name: WLP_LOGGING_CONSOLE_FORMAT
            value: json
          - name: WLP_LOGGING_CONSOLE_SOURCE
            value: message,ffdc,trace
{{- end }}
{{- if .Values.global.disableLogFiles }}
          - name: WLP_LOGGING_MESSAGE_FORMAT
            value: json
          - name: WLP_LOGGING_MESSAGE_SOURCE
            value: none
{{- end }}
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: Always
{{- if .Values.global.healthCheck }}
# No startup probe, as this microservice has to be on MicroProfile 3.x due to MP Reactive Messaging 1.0
# being allergic to MicroProfile 4.x (where startup probes were introduced) in Open Liberty at the moment
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9080
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
{{- end }}
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
            ephemeral-storage: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
            ephemeral-storage: 32Mi
{{- if .Values.tradeHistory.autoscale }}
---
#Deploy the autoscaler
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-trade-history-hpa
  labels:
    app: stock-trader
spec:
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Min
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 120
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-trade-history
  minReplicas: {{ .Values.tradeHistory.replicas }}
  maxReplicas: {{ .Values.tradeHistory.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.tradeHistory.cpuThreshold }}
{{- end }}
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-trade-history-service
{{- if .Values.global.monitoring }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "9080"
{{- end }}
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  #type: NodePort
  ports:
  # the port that this service should serve on
  - name: http
    port: 9080
  - name: https
    port: 9443
  selector:
    app: trade-history
{{- end }}
